[tool.poetry]
name = "superagentx"
version = "0.1.0"
description = "The Ultimate Modular Autonomous Multi AI Agent Framework."
authors = ["SuperAgentX AI <prabhu@decisionfacts.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<=3.13"
pydantic = "^2.8.2"
boto3 = "^1.35.8"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.32"}
psycopg2-binary = "^2.9.9"
pymysql = "^1.1.1"
oracledb = "^2.4.1"
pymssql = "^2.3.1"
pytest = "^8.3.2"
aiosqlite = "^0.20.0"
pytest-asyncio = "^0.24.0"
asyncpg = "^0.29.0"
aiomysql = "^0.2.0"
pyodbc = "^5.1.0"
aioodbc = "^0.5.0"
pandas = "^2.2.2"
bokeh = "^3.5.2"
jira = "^3.8.0"
wikipedia = "^1.4.0"
geopy = "^2.4.1"
timezonefinder = "^6.5.2"
openmeteo-requests = "^1.3.0"
requests-cache = "^1.2.1"
retry-requests = "^2.0.0"
openai = "^1.47.1"
python-dotenv = "^1.0.1"
exa-py = "^1.1.4"
neo4j = "^5.24.0"
chromadb = "^0.5.5"
opensearch-py = "^2.7.1"
elasticsearch = "^8.15.1"
google-auth-oauthlib = "^1.2.1"
google-api-python-client = "^2.147.0"
aiohttp = "^3.10.8"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"